Add files
itk-dev/freescout-itk-prometheus pull request #1
Opened 2024-09-23 07:40 UTC by martinyde

2024-09-23 08:10 UTC, cableman requested changes
Please add return types to all functions

2024-09-23 08:10 UTC, cableman commented on CHANGELOG.md
> +* Implements incBy counter
Please use keep-a-change-log format - and the inline links for versions. See their log: https://github.com/olivierlacan/keep-a-changelog/blob/main/CHANGELOG.md?plain=1

2024-09-23 08:10 UTC, cableman commented on Http/Controllers/ItkPrometheusController.php
> +  /**
Indention wrong...

2024-09-23 08:10 UTC, cableman commented on Http/Controllers/ItkPrometheusController.php
> +     * @return Response
Normally we have an empty line between the different doc block types. But I do not known what the coding standard for freescout is.

2024-09-23 08:10 UTC, cableman commented on Http/Controllers/ItkPrometheusController.php
> +    }
Empty function? If required here, please make note that it is left empty.

2024-09-23 08:10 UTC, cableman commented on Http/Controllers/ItkPrometheusController.php
> +    }
Same here as with `store`

2024-09-23 08:10 UTC, cableman commented on Providers/ItkPrometheusServiceProvider.php
> +        $this->hooks();
Why have this call to an empty `hooks()` function... if real need please comment why

2024-09-23 08:10 UTC, cableman commented on Public/js/laroute.js
> +(function () {
Why is this JS code need and what do it do?

2024-09-23 08:10 UTC, cableman commented on Service/PrometheusService.php
> +   * @return string
Function comment would be nice to have. I think it renders the metrics end-point for scraping ?

2024-09-23 10:34 UTC, martinyde commented on Http/Controllers/ItkPrometheusController.php
> +  /**
Fixed

2024-09-23 10:45 UTC, cableman requested changes

2024-09-23 10:45 UTC, cableman commented on CHANGELOG.md
> +## [1.0.0] - 2024-09-23
You need to make the links in the bottom to male the [version] into links. See https://github.com/itk-dev/economics/blob/develop/CHANGELOG.md?plain=1#L340

2024-09-23 10:45 UTC, cableman commented on Service/PrometheusService.php
> +  public function incCounterBy(array $counter, array $labels, int $count = 1): void {
All functions need the return types specified link this one has `: void`

2024-09-23 10:47 UTC, martinyde commented on CHANGELOG.md
> +## [1.0.0] - 2024-09-23
Removed version

2024-10-03 16:25 UTC, cableman approved these changes

2024-10-08 09:28 UTC, merged